### ISSUE TITLE
Make the "Welcome message" toggleable

### ISSUE THREAD

**Issue by polki92** [Mctalian/RPGLootFeed#101]
Hey !

Could be nice to be able to have a toggle ON/OFF for the "Welcome message".

Because if every addon make it default ON, chat would be spammed after each /reload or upon logging in :p 

Thanks for your awesome work btw !

**Comment by Mctalian** [comment]
Great point! I'll make that happen

**Comment by Mctalian** [comment]
@polki92 

What if I have it pop up once per version? So if I release new features or change the message at some point, it won't be hidden indefinitely.

**Comment by polki92** [comment]
Yeah why not ? Also add the version to the welcome message ? not sure if this is useful or not tho.

**Comment by Mctalian** [comment]
Yeah that's exactly what I was thinking!
