### ISSUE TITLE
Allow us to change the default maximum amount of rows

### ISSUE THREAD

**Issue by polki92** [Mctalian/RPGLootFeed#102]
The minimal settings for "Maximum amount of rows" is hard set to 10.

Not sure why but it would be nice if we could set it to whatever we want below 10.

**Comment by polki92** [comment]
Also what happens if I set this limit to 10, but I loot 15 different items at the same time ?
Will it show the first 10 items looted, wait for the set delay, then display the remaining 5 ?

**Comment by Mctalian** [comment]
I need to add a queue system. Right now, it just drops the extra 5 items on the floor 😬

I've thought about this and haven't made a ticket yet for that. I'll spin a ticket off from here. 

I can adjust the max row settings, though!

**Comment by Mctalian** [comment]
The queue system is probably needed first. That's probably why I locked it to 10 since loot alerts would be lost otherwise.

**Comment by polki92** [comment]
I think that if you allow new users to go below 10 for the limit, and they it to like 3-4, then they will be confused when they drop more than 3-4 items until you add that queue system

**Comment by Mctalian** [comment]
I think I thought of a good way to handle the queue but it'll require some rework. I'll try to get both of these issues in for v1.6.0 🤞
