### ISSUE TITLE
Bug: attempt to index global 'self' (a nil value)

### ISSUE THREAD

**Issue by mrchops1024** [Mctalian/RPGLootFeed#109]
Version: `1.6.0`

Error message:

> Message: Interface/AddOns/RPGLootFeed/Features/ItemLoot.lua:48: attempt to index global 'self' (a nil value)
> 
> ==== Addon Info RPGLootFeed v1.6.0-1-f1ef139 ====
> 
> Log traces related to ItemLoot
> -------------------------------------------------
> [16:59:53]{I}(WOW)[ITEM] :CHAT_MSG_LOOT You create: [Conjured Mana Bun]x20.
> [16:59:35]{I}(WOW)[ITEM] :CHAT_MSG_LOOT You create: [Conjured Mana Bun]x20.
> -------------------------------------------------
> 
> Please report this issue @ github: McTalian/RPGLootFeed
> 
> 
> Time: Mon Sep  9 16:59:53 2024
> Count: 1
> Stack: Interface/AddOns/RPGLootFeed/Features/ItemLoot.lua:48: attempt to index global 'self' (a nil value)
> 
> ==== Addon Info RPGLootFeed v1.6.0-1-f1ef139 ====
> 
> Log traces related to ItemLoot
> -------------------------------------------------
> [16:59:53]{I}(WOW)[ITEM] :CHAT_MSG_LOOT You create: [Conjured Mana Bun]x20.
> [16:59:35]{I}(WOW)[ITEM] :CHAT_MSG_LOOT You create: [Conjured Mana Bun]x20.
> -------------------------------------------------
> 
> Please report this issue @ github: McTalian/RPGLootFeed

**Comment by Mctalian** [comment]
Thank you! I'll get this fixed asap!

**Comment by mrchops1024** [comment]
Just an update, it appears to be almost anything I loot throws this error.

**Comment by Mctalian** [comment]
Good to know, sounds like I just missed something simple, should be a quick fix

**Comment by Mctalian** [comment]
Ah looks like you've got quality filters on. I see what needs to change, I'll get a quick update once I get to my PC

**Comment by mrchops1024** [comment]
You are correct, I should have added that. I was waiting for the loot history to be implemented before I re-enable all loot categories. Thanks for the quick response.

**Comment by Mctalian** [comment]
`/rlf loot` will show a window with loot messages. I found it super helpful for testing and debugging but Idk how useful it will be for players. Open for feedback on it!

**Comment by Mctalian** [comment]
@mrchops1024 v1.6.1 should be available on the big 3 addon sites soon 🤞🏼 - thank you for the report!

Let me know what you are looking for in a loot history window and I can make some adjustments to fit your needs.

**Comment by mrchops1024** [comment]
> @mrchops1024 v1.6.1 should be available on the big 3 addon sites soon 🤞🏼 - thank you for the report!

So far, so good. Appreciate the quick fix.

> Let me know what you are looking for in a loot history window and I can make some adjustments to fit your needs.

I'm not sure if this thread is the right place, but something like an 'activated-when-hovered-over' window that you can scroll up/down through. I like that I can filter on item quality and have a dedicated place to see loot history, for when I'm not paying attention to my chat window.

When I installed the addon, the first thing I tried to do was see if I could 'un-hide' the loot area to see the history. It seemed like an intuitive feature to have, and would suffice for me.
