### ISSUE TITLE
Show party loot

### ISSUE THREAD

**Issue by Revnae** [Mctalian/RPGLootFeed#112]
How do you enable so other ppls loot show up? thought i saw that in you loot history issue

**Comment by Mctalian** [comment]
You are correct it was mentioned in that issue but I didn't do anything special for party loot (whoops). You can access the loot history with `/rlf log` - though no info on other players' loot right now (or at least no filtering, I do think the wow events might show up).

I need to think about how to show party loot without getting things too cluttered 🤔

**Comment by Mctalian** [comment]
Ok I have an idea on how to handle this! I have a few other things I need to finish first to enable this work, thanks for the issue!

**Comment by Revnae** [comment]
No worries , it just makes the game at little bit more social 😄👍
