### ISSUE TITLE
Right-alignment broken

### ISSUE THREAD

**Issue by Lunaeria** [Mctalian/RPGLootFeed#131]
Just updated the addon and noticed that it was defaulting to left alignment, so I went into the settings and ticked/unticked the option for left alignment, to try to get back to right, but now it's just broken, unfortunately. Picture attached to show what it looks like! Love the addon nonetheless, thanks for all your hard work!

![World Of Warcraft Screenshot 2024 09 23 - 18 13 25 74](https://github.com/user-attachments/assets/3df65eb2-6e2d-4f74-bab1-d8c7429ebb93)

**Comment by Mctalian** [comment]
Oh thanks! I'll try to get this fixed ASAP

**Comment by Mctalian** [comment]
v1.7.2 release is underway and has this fixed, thanks for your patience!
