### ISSUE TITLE
Enlarged loot entry gets stuck on screen periodically

### ISSUE THREAD

**Issue by Lunaeria** [Mctalian/RPGLootFeed#147]
Hello, time for the least helpful bug report ever, yay!

The newest version of the addon has, as far as I can tell, fixed all the performance issues that were previously reported. Haven't had any freezes since upgrading. However, with this new version, every so often, one of the loot entries that pop up in the feed will appear much larger than usual, and will get "stuck" (i.e. won't fade out as it should, until /reload).

This screenshot shows it happening with reputation, but I've had it happen with currency as well:
![World Of Warcraft Screenshot 2024 10 01 - 18 27 29 90](https://github.com/user-attachments/assets/4e3af82b-89e1-4537-b530-bd1ecdbe9185)

There aren't any lua errors associated with it, and (so far) I've not been able to pinpoint a specific situation that it happens in. If I figure that out, I'll let you know ASAP! Similarly, if there's anything I can do to help you troubleshoot this, just let me know.

Thanks so much for all your hard work!

**Comment by Mctalian** [comment]
Bummer! I put some code in to hopefully catch things like this and throw an error. I noticed "stuck" rows myself but haven't been able to find a way to force it to happen.

Welp, at least it's not performance related!

Yes if you happen to find scenarios where it happens regularly, let me know! I'll keep an eye out myself.

Though the scaling/sizing of the row is an interesting piece that I hadn't seen before 🤔

**Comment by arcadepro** [comment]
Same here, yes. Happens pretty much all the time now.
![image](https://github.com/user-attachments/assets/0c01415b-de79-4703-be42-4ed87033f4ac)

**Comment by Mctalian** [comment]
@arcadepro and no Lua errors for you either? 😞

**Comment by Mctalian** [comment]
Alright y'all - give this a shot: https://github.com/Mctalian/RPGLootFeed/actions/runs/11136148467/artifacts/2003794886

**Comment by Lunaeria** [comment]
Just installed this test version, and when I logged in, I got this error. Not sure if it's related to this bug, but here it is, just in case:

`1x RPGLootFeed/SmokeTest.lua:182: Failure: LootDisplay: Item failed: expected true, got false|nFailure: LootDisplay: Item Quantity Update failed: expected true, got false|n
[string "=[C]"]: in function `error'
[string "@RPGLootFeed/SmokeTest.lua"]:182: in function `SmokeTest'
[string "@RPGLootFeed/TestMode.lua"]:103: in function `?'
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AngrierWorldQuests/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ngrierWorldQuests/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "|cffff0000Failure: LootDisplay: Item failed: expected true, got false|r|n|cffff0000Failure: LootDisplay: Item Quantity Update failed: expected true, got false|r|n"
`

**Comment by Mctalian** [comment]
Thanks @Lunaeria - likely not related but I'll keep this in mind. Those are just tests that I run on alpha builds to make sure things are still working. I don't encounter that failure, so that's a bit interesting 🤔

**Comment by Mctalian** [comment]
I actually think the stuck rows are due to cutscenes and other things that force hide the UI (Trading Post vendor, probably barber shop, even pressing Alt+Z).

So if that's the case, I believe that the test build above will have fixed that. If not, let's keep digging!

@Lunaeria - regarding the Smoke Test errors on login, this build (https://github.com/Mctalian/RPGLootFeed/actions/runs/11148488063/artifacts/2007142789) should actually include the error messages in the Lua error 🤞🏼 (but I am not seeing the same failure, so I can't fully test that). It is strange to me how different our experiences are 🤔 I wonder what part of our PC builds are so different that it's causing this? Something I'm thinking about, more of a rhetorical question right now. If you're able to try it, great, if not, no worries.

Here's my own dxdiag system output just in case. My CPU is ~5 years old I think so it's not like I'm not the newest, top-of-the-line hardware.
![image](https://github.com/user-attachments/assets/0c2536bb-25f0-464f-a1ca-b36cc35323ff)

**Comment by Lunaeria** [comment]
I do use Dialogue UI, which hides the UI whenever I'm talking to an NPC, so that would make a lot of sense if it's the source of the stuck rows. I'll let you know if the issue pops up again!

As for the new test build, I've just installed it and I didn't get any errors during the Smoke Test upon login, so it seems it's all good for now? Again, will let you know if anything changes!

Just for your own reference/interest, here's my own dxdiag output:
![Screenshot 2024-10-02 200445](https://github.com/user-attachments/assets/b609b3ff-3ab7-43d2-b264-28d62be95992)
(Though, since there's no errors in the Smoke Test now, perhaps that one time was just a fluke? Who knows!)

**Comment by Mctalian** [comment]
Awesome thank you! This is starting to make sense. You'll see a lot of print noise in those test builds when it detects what would have caused a stuck row. But I'm becoming more confident that once I remove the prints, the stuck rows will go away.

I'll start looking at the Dialogue UI code and see what's going on behind the scenes so I can try to prevent the weird scaling too.

**Comment by Mctalian** [comment]
Sweet! I'll plan on releasing a fix later this evening or tomorrow morning unless I hear that you're still seeing the issues. Thanks for your help in tracking this down! 🤞 Hopefully we got it!

**Comment by Mctalian** [comment]
Whoops, it got auto-closed, but I feel pretty good about the fix 😄 🤞🏼 - if it didn't completely fix it, we'll open it back up and try again

**Comment by Lunaeria** [comment]
I've been playing with the fix the whole time since you linked it, and I've not had the problem happen even once, so it seems like you figured it out! I'll obviously still update you if I run into it again, but for now, everything seems to be running smoothly. Thanks for all your hard work!

**Comment by arcadepro** [comment]
Differences between peoples outcomes are more likely to be attributed to addons rather than PC specs. i.e. you will have some addons installed that the user hasn't and vice versa.

**Comment by Mctalian** [comment]
That's true, it does seem to be addons conflicting with each other.
