### ISSUE TITLE
PVP Currency rewards from the Weekly 'Sparks of War' Quest report the wrong value.

### ISSUE THREAD

**Issue by arcadepro** [Mctalian/RPGLootFeed#150]
The reward from the quest is 1000 coins but you can only earn upto the cap. In the following example I received 350 coins (confirmed with combat log). There are two extraneous zeros added to it. The same seems to apply to Conquest points. Unsure of the other currency there.

![image](https://github.com/user-attachments/assets/c8bd8856-a605-4ccb-967a-c2de2bc5dc1e)

I'll get more log info when I can repeat the quest.

**Comment by Mctalian** [comment]
Thanks for the report! I haven't done any PVP since I made this addon, so it's definitely a blind spot. I'll look into it!

**Comment by Mctalian** [comment]
I'll be able to take more of a look at this the rest of this week. I've been a bit busy beginning a transition to my new job but I should have some free time the next few days.

**Comment by Mctalian** [comment]
There should be a WOWEVENT Info Currency log for this event: `CURRENCY_DISPLAY_UPDATE` that will have the quantity change that is included in the event from Blizzard. I am curious if you see it again this week if you can provide me those lines from the logs. Looking at the code, I'm not doing anything too complicated in the Currency feature, so I wonder if the blizzard event is coming over with a weird value. If the value is correct, I'll have to look a little deeper and figure out where the extra values are coming in.

**Comment by byezero** [comment]
I have to say, recently, for the experience boost, I turned on the PvP switch, and the PvP currency definitely has two more zeros. By the way, the performance issue seems to have been resolved in 1.7.7, and I will do further testing when I have time.

**Comment by Mctalian** [comment]
Strange about the PVP currency. If anyone sees it, please run `/rlf log` and turn on the WOWEVENTS source and paste the details here. That will really help me track this down. I haven't had time to do any PVP lately so it'll take me a while to get to the bottom of this on my own without logs.

Good to hear about v1.7.7 - hopefully that continues!

**Comment by Mctalian** [comment]
This should fix it: https://github.com/Mctalian/RPGLootFeed/actions/runs/11350426382/artifacts/2059154223
