### ISSUE TITLE
Look into FPS stutter

### ISSUE THREAD

**Issue by Mctalian** [Mctalian/RPGLootFeed#151]
From Reddit post: 

https://www.reddit.com/r/wow/s/EQttjfqHlY

**Comment by byezero** [comment]
Yes, I also found that after enabling the addon will cause the game to jam, currently disabled

**Comment by Mctalian** [comment]
@byezero the game completely freezes? On version v1.7.6?

**Comment by byezero** [comment]
No, it will cause fps to decrease, especially when flying.

**Comment by Mctalian** [comment]
Thanks, I'll try to figure out what's going on

**Comment by byezero** [comment]
There were no problems before the update, and you can see if the latest update monitored too many events or something.

**Comment by Mctalian** [comment]
@byezero so v1.7.5 you had no issues, v1.7.6 you have this lag? I just want to make sure I'm comparing the correct versions. Thanks!

**Comment by byezero** [comment]
I'm not sure, but it basically updates every few days, and the date that it appears is 24/10/05

**Comment by Mctalian** [comment]
Ok, no worries. Many had issues between version v1.6.2 and v1.7.0 so I was just trying to figure out which two versions needed to be compared. I'll do some tests and see if I experience FPS drops on my own PC. I'll figure out the root cause, thank you!

**Comment by byezero** [comment]
emmm, I read the previous issues, I also used DialogueUI, and during the National Day holiday in China, I used a computer with poor hardware performance.

**Comment by Mctalian** [comment]
I'll be able to take more of a look at this the rest of this week. I've been a bit busy beginning a transition to my new job but I should have some free time the next few days.

**Comment by byezero** [comment]
Congratulations on getting a new offer. Work and life are the most important things. I have returned 1.6.0 and it works very well.

**Comment by Mctalian** [comment]
@byezero see if this build helps with the FPS stutter (https://github.com/Mctalian/RPGLootFeed/actions/runs/11335264324/artifacts/2055182826)

It's an alpha build, so you may see more chat messages than usual, but hopefully FPS stabilizes.

**Comment by Mctalian** [comment]
I think I solved this in v1.7.7 - let me know if you see improvements 🤞🏼
