### ISSUE TITLE
FPS stutter when looting

### ISSUE THREAD

**Issue by Rostas** [Mctalian/RPGLootFeed#152]
RPGLootFeed-v1.7.6

Stutter when looting an item

It seems to only happen in Hallowfall then it stays afterwards

**Comment by Mctalian** [comment]
Thanks for the report! I'll track this as part of #151 - I'm looking into it just haven't been able to see it on my own PC yet.

**Comment by Mctalian** [comment]
@Rostas you can try v1.6.2 - it sounds like most folks don't see any lag issues in that version. I'll try to release a fix this week to fix these performance issues.

**Comment by Mctalian** [comment]
I think I solved this in v1.7.7 - let me know if you see improvements 🤞🏼
