### ISSUE TITLE
Highlight rare drops (legendary, mount, mount skins)

### ISSUE THREAD

**Issue by Pegoth** [Mctalian/RPGLootFeed#161]
It would be nice if I would be able to set an animation, or border or something to highlight drops that are note worthy (e.g legendary, mount, mount skins).

**Comment by Mctalian** [comment]
Thanks for using RPGLootFeed and for submitting the idea!

**Comment by Mctalian** [comment]
@Pegoth I am planning on getting this in for v1.9.0 - do you have any other criteria for noteworthy loot? Legendary, mounts, and mount skins should be pretty straightforward, but I was wondering if you had any other ideas pop up over the past 3 weeks?

**Comment by Pegoth** [comment]
Not really, maybe add a custom fields that the user can type values (name or id) into to highlight it?

**Comment by Mctalian** [comment]
Cool I'll keep these in mind and create some extra tickets if it's more effort than I was hoping for. Good ideas!

**Comment by Mctalian** [comment]
![RLF_MountHighlight_3](https://github.com/user-attachments/assets/657b3b52-d43f-4de8-b7e3-3f66cb8baca4)

Here's what I have so far. I'll probably change the animation a bit, but wanted to see what your thoughts were on the direction.

**Comment by Mctalian** [comment]
I like this one better:
![RLF_MountHighlight_new](https://github.com/user-attachments/assets/9e9415fd-e302-4f08-adbb-89efde8be107)

**Comment by Pegoth** [comment]
The second one is more obvious and more WoW like, but I still like the first one better. When you cannot make a choice, make it an option!

**Comment by Mctalian** [comment]
Both of them were setup a little differently aside from just the animations, so I will see if I keep them both and make an option. If not I'll revisit this later as I have other ideas for expanding animations in other areas and I can add in more options here as well. We'll see how it all shakes out as I plan to get v1.9.0 out pretty soon.
