### ISSUE TITLE
Low amount of money display as 0

### ISSUE THREAD

**Issue by polki92** [Mctalian/RPGLootFeed#17]
Making a new char ( dwarf for example, lots of humanoird dropping money ), looted some copper. The addon displays "0 copper" looted.

**Comment by polki92** [comment]
Ok found where it comes from.
Sionce the addon is reading the chatlogs, it only reads english terms.

Switched to english client and it's working but would be nice if you could add support to different languages :) 
( FR / DE / ES   being the main )

**Comment by Mctalian** [comment]
Thanks for finding the root cause!

Ideally, I will be able to find a way to _not_ use the chat for things like this, but I haven't been able to find a suitable replacement yet.

I will add a broader ticket for localization support because I'm sure there are more gotchas out there.

**Comment by Mctalian** [comment]
@polki92 do you happen to have a screenshot or can you type out what the Money loot looks like in the language you play?

I may be able to do something a little different as a quick fix before I can focus on full-on localization support

**Comment by Mctalian** [comment]
This should be good to go in v1.1.3, let me know if this doesn't work for you @polki92
