### ISSUE TITLE
Add an option to choose between left align and right align

### ISSUE THREAD

**Issue by polki92** [Mctalian/RPGLootFeed#18]
I would prefer the addon to display on the right side of the screen but the alignement is left by default.

Could be nice to have an option that let us choose between left or right align.

( I managed to align the loot display to the right inside LootDisplay.lua but it will get removed with every patch :p )

**Comment by Mctalian** [comment]
Good idea and good point!

I think this one should be pretty straightforward. I'll look into getting this taken care of soon 👍🏼

**Comment by Mctalian** [comment]
This should be good to go in v1.1.3 - let me know if you run into any issues @polki92
