### ISSUE TITLE
TSM/Auctionator

### ISSUE THREAD

**Issue by cheeseslicer** [Mctalian/RPGLootFeed#20]
Add functionality to show tsm value based on users input such as, minbuyout, regionavg. so on and so forth. on top of value for vendoring item. 

I know there is a WA that has something similar, but he isn't updating it anymore i don't believe and so it never works anymore without causing errors thanks to the new api blizz introduced.

**Comment by Mctalian** [comment]
Thanks @cheeseslicer!

I'm not 100% sure I follow this request. It sounds like you're looking for auction data on the item tooltip? Let me know if I'm off base here!

In the meantime, I'll try to take a look at those add-ons you mentioned to see if that can help me understand a little better.

**Comment by Mctalian** [comment]
Ahhh I think I understand! Here's a weakaura that does something similar but it shows the vendor price (and I guess the TSM/Auctionator data as well, but there's not a screenshot that shows that): https://wago.io/FarmHelper

**Comment by cheeseslicer** [comment]
Close but this one more so
https://wago.io/-IWPKK1il

**Comment by Mctalian** [comment]
@cheeseslicer I finally finished up some of the foundational work to get this going, so I am targeting to get this in to v1.9.0 - let me know if you have any other thoughts on this!
