### ISSUE TITLE
Chinese support, add reputation and experience display features

### ISSUE THREAD

**Issue by byezero** [Mctalian/RPGLootFeed#29]
I am a Chinese player, and I hope the plugin can add support for Chinese. For this, I am willing to help with the translation.
I saw that other issues mentioned adding the display of experience and reputation, which is also a feature I urgently need.
Thank you to the author for contributing such a great plugin, it is indeed a good innovation.
My English is not good, this is translated using artificial intelligence, I apologize if there are any difficulties in understanding.

**Comment by Mctalian** [comment]
Thank you! I will add a Chinese locale file and a ticket for translation requests.

I'll prioritize experience and reputation as well.

**Comment by Mctalian** [comment]
@byezero #37 has been created, let me know if you need any support!
