### ISSUE TITLE
Loots are displayed as only x1

### ISSUE THREAD

**Issue by polki92** [Mctalian/RPGLootFeed#50]
Major issue I guess.

The loot feed only shows x1 of each loot despite looting stacks 

![image](https://github.com/user-attachments/assets/722c9676-dbd0-4ad7-a223-89d8e3ba3341)
![image](https://github.com/user-attachments/assets/acdecbbc-1f1d-412f-b215-05ebf52be018)

**Comment by Mctalian** [comment]
Interesting. Is this from gathering like herbalism? I wasn't seeing this myself. I'm wondering if it's possibly a locale issue 🤔

I'll try to figure out what's going on, thanks!

**Comment by polki92** [comment]
Not only gathering. First screen are herbs, second is trash from mobs. 
Every loot affected and yes I think it's a locale issue

**Comment by Mctalian** [comment]
I also wonder if maybe it's related to early access. Do you see this outside of The War Within content?

Either way, I'll look into it as soon as I can!

Thanks for the report 💚

**Comment by Mctalian** [comment]
@polki92 give v1.3.3 a try, if you can, once it gets approved on CurseForge / WoWI / Wago. Should be available any minute now 🤞🏼
