### ISSUE TITLE
Incorrect calculation of reputation

### ISSUE THREAD

**Issue by ffainy** [Mctalian/RPGLootFeed#58]
For example, my current reputation is 2400/2500, when I complete a quest that gives 300 reputation, addon will show -2300 🤣

**Comment by Mctalian** [comment]
Whoops, I guess I mathed wrong. I'll talk a look at that tomorrow!

**Comment by Mctalian** [comment]
Is this with a major faction? I have rep split into 3 separate groups so I just want to make sure I focus on the correct group.

**Comment by ffainy** [comment]
ran into this problem while doing the Maruuk Centaur mission

**Comment by ffainy** [comment]
did more testing and what happens is that the addon miscalculates as soon as you gain more rep than the current stage into the next stage.

**Comment by Mctalian** [comment]
Thanks for the report and for helping narrow down the problem!

I know the problematic line of code, just need to figure out the fix 😅

**Comment by Mctalian** [comment]
Figured it out! Looks like the rep comes in first, but the level up lags behind. So I had the correct logic/math, but I didn't account for the level up being delayed.
