### ISSUE TITLE
Strange words appear from time to time

### ISSUE THREAD

**Issue by ffainy** [Mctalian/RPGLootFeed#64]
Often this strange text appears when I loot or open a reward chest

![image](https://github.com/user-attachments/assets/a8d8d0c4-568e-4803-b657-b601585c2f42)

**Comment by Mctalian** [comment]
I noticed that as well, typically when I was playing remix. I haven't figured out where it's coming from yet. I thought it was related to unlocking appearances but it doesn't seem consistent.

If we can find a way to consistently make it appear, I can track down the source.

I'll keep an eye out myself 🤞

**Comment by Mctalian** [comment]
A quick Google search links it to a hidden currency that seems to be related to Flightstones? Bit I can only find it on Russian and Spanish wowhead pages. 🤔

**Comment by ffainy** [comment]
more🤣

![image](https://github.com/user-attachments/assets/dd40b702-0d7d-4df4-9704-92426a5c8d66)

**Comment by Mctalian** [comment]
I think I should have it fixed, but I need to do some testing before I release
