### ISSUE TITLE
Configuration for fonts

### ISSUE THREAD

**Issue by Mctalian** [Mctalian/RPGLootFeed#9]
The font face and font size are locked to a static value.

Add a configuration option for the font face and/or font size.

**Comment by Mctalian** [comment]
I nearly had this done, but I kind of didn't like how things felt. I may revisit this later unless there are people who really want this.

**Comment by polki92** [comment]
> I nearly had this done, but I kind of didn't like how things felt. I may revisit this later unless there are people who really want this.

I do personally since I can't read default font :-/

I modify your files after each update to add my own font tho :>

**Comment by Mctalian** [comment]
Sounds good! I'll take another look at this.
